print("*" , end=" ")
print("*" , end=" ")
print("*" , end=" ")
print()
print("*" , end=" ")
print("*" , end=" ")
print("*" , end=" ")
print()
print("*" , end=" ")
print("*" , end=" ")
print("*" , end=" ")
print()
print("__________________________________________________________________________________")
print()
for i in range(3):
    print("*" , end=" ")
print()
for i in range(3):
    print("*" , end=" ")
print()
for i in range(3):
    print("*" , end=" ")
print()
print("__________________________________________________________________________________")
print()
for i in range(3):
    for i in range(3):
        print("*",end=" ")    
    print()
#                            &Here We Are& 
print("__________________________________________________________________________________")
print()
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print()
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print()
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print()
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print()
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print()
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print("*",end=" ")
print()
print("----------------------------------------------------------------------------------")
print()
for i in range(6):
    print("*",end=" ")
print()
for i in range(6):
    print("*",end=" ")
print()
for i in range(6):
    print("*",end=" ")
print()
for i in range(6):
    print("*",end=" ")
print()
for i in range(6):
    print("*",end=" ")
print()
for i in range(6):
    print("*",end=" ")
print()
print("----------------------------------------------------------------------------------")
print()
for i in range(6):
    for i in range(6):
       print("*",end=" ")
    print()